name: Build (no deploy)

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prime-focus-cafe
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: prime-focus-cafe/package-lock.json
      - run: npm ci
      - run: npm run build
