name: Deploy Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  BUCKET: www.primefocususa.com-site
  CF_DIST_ID: E32K05VBG79GEL

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prime-focus-cafe

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: prime-focus-cafe/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::831926590271:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ env.BUCKET }} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths "/*"
